name: Test and Lint
on:
  workflow_call:
    secrets:
      DOCKERHUB_USER:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:

  job1-ubuntu:
    name: Job1 ubuntu-22.04
    runs-on: ubuntu-22.04
    if: ${{ github.server_url == 'https://github.com' }}  # Directly check server URL
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Debug submodule content
        run: |
          echo "Listing .github/actions/docker-login:"
          ls -la .github/actions/docker-login
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: echo job1-ubuntu
        run: echo "job1-ubuntu"
      # - name: Test
      #   run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      # - name: Lint
      #   run: docker compose run --rm app sh -c "flake8"

  windows-exec:
    name: Windows exec
    runs-on: [self-hosted, Windows]
    if: ${{ github.server_url != 'https://github.com' }}  # Directly check server URL
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0
      - name: Assume role
        shell: pwsh
        run: ./bin/assume_terraform_role.ps1 ma-recipe-app-terraform-role

  # Final Status Check
  final-status:
    needs: [job1-ubuntu, windows-exec]
    runs-on: ${{ (github.server_url == 'https://github.com' && 'ubuntu-22.04') || 'self-hosted' }}
    if: always()
    steps:
      - name: Determine Workflow Status
        shell: pwsh
        run: |
          Write-Output "Evaluating job results..."
          # Initialize overall result as success
          $OVERALL_RESULT = "success"

          # Check if job1-ubuntu job ran and its result
          if ("${{ needs.job1-ubuntu.result }}" -eq "failure") {
            Write-Output "job1-ubuntu failed."
            $OVERALL_RESULT = "failure"
          }

          # Check if windows-exec job ran and its result
          if ("${{ needs.windows-exec.result }}" -eq "failure") {
            Write-Output "windows-exec failed."
            $OVERALL_RESULT = "failure"
          }

          Write-Output "Overall result: $OVERALL_RESULT"
          if ($OVERALL_RESULT -eq "success") {
            exit 0
          } else {
            exit 1
          }
